---
- hosts: west
  tasks:
    - include: tasks/backup-wordpress.yml
      tags: [biscuitman, backup]
      vars:
        dbcontainer: "{{ biscuitman.db.container }}"
        dbname: "{{ biscuitman.db.name }}"
        dbpassword: "{{ biscuitman.db.password }}"
        dbuser: "{{ biscuitman.db.user }}"
        wpcontainer: "{{ biscuitman.wp.container }}"

    - include: tasks/backup-wordpress.yml
      tags: [biscuit-stage, backup]
      vars:
        dbcontainer: "{{ biscuit_stage.db.container }}"
        dbname: "{{ biscuit_stage.db.name }}"
        dbpassword: "{{ biscuit_stage.db.password }}"
        dbuser: "{{ biscuit_stage.db.user }}"
        wpcontainer: "{{ biscuit_stage.wp.container }}"

    - include: tasks/backup-wordpress.yml
      tags: [bowen, backup]
      vars:
        dbcontainer: "{{ bowen.db.container }}"
        dbname: "{{ bowen.db.name }}"
        dbpassword: "{{ bowen.db.password }}"
        dbuser: "{{ bowen.db.user }}"
        wpcontainer: "{{ bowen.wp.container }}"

    - include: tasks/backup-wordpress.yml
      tags: [joel, backup]
      vars:
        dbcontainer: "{{ joel.db.container }}"
        dbname: "{{ joel.db.name }}"
        dbpassword: "{{ joel.db.password }}"
        dbuser: "{{ joel.db.user }}"
        wpcontainer: "{{ joel.wp.container }}"

    - include: tasks/backup-wordpress.yml
      tags: [just-us, backup]
      vars:
        dbcontainer: "{{ just_us.db.container }}"
        dbname: "{{ just_us.db.name }}"
        dbpassword: "{{ just_us.db.password }}"
        dbuser: "{{ just_us.db.user }}"
        wpcontainer: "{{ just_us.wp.container }}"

    - include: tasks/backup-wordpress.yml
      tags: [mmm, backup]
      vars:
        dbcontainer: "{{ mmm.db.container }}"
        dbname: "{{ mmm.db.name }}"
        dbpassword: "{{ mmm.db.password }}"
        dbuser: "{{ mmm.db.user }}"
        wpcontainer: "{{ mmm.wp.container }}"

    - include: tasks/backup-wordpress.yml
      tags: [platypus, backup]
      vars:
        dbcontainer: "{{ platypus.db.container }}"
        dbname: "{{ platypus.db.name }}"
        dbpassword: "{{ platypus.db.password }}"
        dbuser: "{{ platypus.db.user }}"
        wpcontainer: "{{ platypus.wp.container }}"

    - include: tasks/backup-wordpress.yml
      tags: [shahbaz, backup]
      vars:
        dbcontainer: "{{ shahbaz.db.container }}"
        dbname: "{{ shahbaz.db.name }}"
        dbpassword: "{{ shahbaz.db.password }}"
        dbuser: "{{ shahbaz.db.user }}"
        wpcontainer: "{{ shahbaz.wp.container }}"

    - include: tasks/archive-backups.yml
      tags: archive

    - include: tasks/fetch-archives.yml
      tags: archive

  vars_files:
    - play_vars/biscuitman-stage.yml
    - play_vars/biscuitman.yml
    - play_vars/bowen-work.yml
    - play_vars/joel.yml
    - play_vars/just-us.yml
    - play_vars/my-market-mentor.yml
    - play_vars/platypus.yml
    - play_vars/shahbaz.yml

- hosts: east
  tasks:
    - include: tasks/backup-wordpress.yml
      tags: [afsheen, backup]
      vars:
        dbcontainer: "{{ afsheen.db.container }}"
        dbname: "{{ afsheen.db.name }}"
        dbpassword: "{{ afsheen.db.password }}"
        dbuser: "{{ afsheen.db.user }}"
        wpcontainer: "{{ afsheen.wp.container }}"

    - include: tasks/backup-wordpress.yml
      tags: [journaling, backup]
      vars:
        dbcontainer: "{{ journaling.db.container }}"
        dbname: "{{ journaling.db.name }}"
        dbpassword: "{{ journaling.db.password }}"
        dbuser: "{{ journaling.db.user }}"
        wpcontainer: "{{ journaling.wp.container }}"

  vars_files:
    - play_vars/afsheen.yml
    - play_vars/journaling.yml
