---
- hosts: east
  tasks:
    - include: tasks/push-archives.yml
      tags: [archive, push]
      vars:
        #TODO make this more dynamic
        localarchivedir: '/$HOME/ansible-fetch/beast/home/hank/archives/'

    - include: tasks/restore-wordpress.yml
      tags: [platypus, restore]
      vars:
        backupdbcontainer: '{{ platypus.db.container }}'
        backupwpcontainer: '{{ platypus.wp.container }}'
        dbcontainer: '{{ platypus.db.container }}'
        dbname: '{{ platypus.db.name }}'
        dbpassword: '{{ platypus.db.password }}'
        dbuser: '{{ platypus.db.user }}'
        wpcontainer: '{{ platypus.wp.container }}'

  vars_files:
    - play_vars/platypus.yml
