---
- hosts: east
  tasks:
    - include: tasks/afsheen.yml
      tags: afsheen
    - include: tasks/biscuit-stage.yml
      tags: biscuit-stage
    - include: tasks/biscuitman.yml
      tags: biscuitman
    - include: tasks/bowen-work.yml
      tags: bowen
    - include: tasks/coolidge.yml
      tags: coolidge
    - include: tasks/drupal-demo.yml
      tags: drupal-demo
    - include: tasks/drupaul.yml
      tags: drupaul
    - include: tasks/ghost-demo.yml
      tags: ghost-demo
    - include: tasks/joel.yml
      tags: joel
    - include: tasks/legiticus.yml
      tags: legiticus
    - include: tasks/just-us.yml
      tags: just-us
    - include: tasks/sudo-science.yml
      tags: sudo-science
    - include: tasks/veta.yml
      tags: veta
    - include: tasks/my-market-mentor.yml
      tags: mmm
    - include: tasks/platypus.yml
      tags: platypus
    - include: tasks/shahbaz.yml
      tags: shahbaz
    - include: tasks/veta.yml
      tags: veta
    - include: tasks/zelda.yml
      tags: zelda
  vars_files:
    - play_vars/afsheen.yml
    - play_vars/biscuitman-stage.yml
    - play_vars/biscuitman.yml
    - play_vars/bowen.yml
    - play_vars/coolidge.yml
    - play_vars/drupal-demo.yml
    - play_vars/drupaul.yml
    - play_vars/ghost-demo.yml
    - play_vars/joel.yml
    - play_vars/legiticus.yml
    - play_vars/just-us.yml
    - play_vars/my-market-mentor.yml
    - play_vars/platypus.yml
    - play_vars/shahbaz.yml
    - play_vars/sudo-science.yml
    - play_vars/veta.yml
    - play_vars/zelda.yml

# These are stopped or suspended until needed
- hosts: nada
  tasks:
    - include: tasks/alien-admin.yml
      tags: alien-admin
    - include: tasks/sabew-legacy.yml
      tags: sabew
    - include: tasks/wordpress-demo.yml
      tags: wordpress-demo
  vars_files:
    - play_vars/alien-admin.yml
    - play_vars/sabew-legacy.yml
    - play_vars/wordpress-demo.yml

- hosts: west
  tasks:
    - include: tasks/beton.yml
      tags: beton
    - include: tasks/commgap.yml
      tags: commgap
    - include: tasks/madeline.yml
      tags: madeline
    - include: tasks/sabew-stage.yml
      tags: sabew-stage
    - include: tasks/such.yml
      tags: such
    - include: tasks/tw-donnie.yml
      tags: [tw, donnie]
    - include: tasks/tw-jenna.yml
      tags: [tw, jenna]
    - include: tasks/tw-oceanic.yml
      tags: [tw, oceanic]
    - include: tasks/tw-sammy.yml
      tags: [tw, sammy]
  vars_files:
    - play_vars/beton.yml
    - play_vars/commgap.yml
    - play_vars/madeline.yml
    - play_vars/sabew-stage.yml
    - play_vars/such.yml
    - play_vars/tw-donnie.yml
    - play_vars/tw-jenna.yml
    - play_vars/tw-oceanic.yml
    - play_vars/tw-sammy.yml
