---
- hosts: webservers
  remote_user: "{{ username }}"
  tasks:
    - name: ensure webapps workdir is present
      file:
        group: "{{ usergroup }}"
        owner: "{{ username }}"
        path: "{{ workdir }}"
        state: directory

- hosts: east
  remote_user: "{{ username }}"
  tasks:
    - include: tasks/my-market-mentor.yml

- hosts: west
  remote_user: "{{ username }}"
  tasks:
    - include: tasks/drupal-demo.yml