---
# - hosts: east
#   tasks:
#   vars_files:

- hosts: west
  tasks:
    - include: tasks/coolidge.yml
      tags: coolidge
    - include: tasks/platypus.yml
      tags: platypus
    - include: tasks/tw-donnie.yml
      tags: [tw, donnie]
    - include: tasks/tw-jenna.yml
      tags: [tw, jenna]
    - include: tasks/tw-oceanic.yml
      tags: [tw, oceanic]
    - include: tasks/tw-sammy.yml
      tags: [tw, sammy]
  vars_files:
    - play_vars/coolidge.yml
    - play_vars/platypus.yml
    - play_vars/tw-donnie.yml
    - play_vars/tw-jenna.yml
    - play_vars/tw-oceanic.yml
    - play_vars/tw-sammy.yml
