---
- name: afsheen wordpress content container
  docker_container:
    image: wordpress:5.4.2
    name: afsheen-content
    state: stopped
    volumes:
      - /var/www/html

- name: afsheen db data container
  docker_container:
    image: mariadb:10.5
    name: afsheen-db-data
    state: stopped
    volumes:
      - /var/lib/mysql

- name: afsheen database
  docker_container:
    image: mariadb:10.5
    name: afsheen-db
    restart_policy: always
    env:
      MYSQL_DATABASE: "{{ afsheen.db.name }}"
      MYSQL_PASSWORD: "{{ afsheen.db.password }}"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: "{{ afsheen.db.user }}"
    volumes:
      - afsheen-db-data:/var/lib/mysql

- name: afsheen wordpress
  docker_container:
    image: wordpress:5.4.2
    name: afsheen-wp
    restart: yes
    restart_policy: always
    env:
      HSTS: "off"
      LETSENCRYPT_HOST: "{{ afsheen_hosts }}"
      VIRTUAL_HOST: "{{ afsheen_hosts }}"
      WORDPRESS_DB_NAME: "{{ afsheen.db.name }}"
      WORDPRESS_DB_PASSWORD: "{{ afsheen.db.password }}"
      WORDPRESS_DB_USER: "{{ afsheen.db.user }}"
    exposed_ports:
      - "80"
    links:
      - "afsheen-db:mysql"
    volumes:
      - afsheen-content:/var/www/html

- name: afsheen sftp
  docker_container:
    command: "{{ afsheen.sftp.user }}:{{ afsheen.sftp.password }}:1001"
    image: atmoz/sftp:latest
    name: afsheen-ftp
    restart_policy: always
    ports:
      - "{{ afsheen_sftp_port }}:22"
    volumes:
      - afsheen-content:/home/afsheen/upload
