---
- name: ascounseling wordpress content container
  docker_container:
    image: wordpress:6.1
    name: ascounseling-content
    state: stopped
    volumes:
      - /var/www/html

- name: ascounseling db data container
  docker_container:
    image: mariadb:10.11
    name: ascounseling-db-data
    state: stopped
    volumes:
      - /var/lib/mysql

- name: ascounseling database
  docker_container:
    image: mariadb:10.11
    name: ascounseling-db
    restart_policy: always
    env:
      MYSQL_DATABASE: "{{ ascounseling.db.name }}"
      MYSQL_PASSWORD: "{{ ascounseling.db.password }}"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: "{{ ascounseling.db.user }}"
    volumes:
      - ascounseling-db-data:/var/lib/mysql

- name: ascounseling wordpress
  docker_container:
    image: wordpress:6.1
    name: ascounseling-wp
    restart: yes
    restart_policy: always
    env:
      LETSENCRYPT_HOST: "{{ ascounseling_hosts }}"
      VIRTUAL_HOST: "{{ ascounseling_hosts }}"
      WORDPRESS_DB_NAME: "{{ ascounseling.db.name }}"
      WORDPRESS_DB_PASSWORD: "{{ ascounseling.db.password }}"
      WORDPRESS_DB_USER: "{{ ascounseling.db.user }}"
    exposed_ports:
      - "80"
    links:
      - "ascounseling-db:mysql"
    volumes:
      - ascounseling-content:/var/www/html

- name: ensure app-files directory exists
  file:
    path: ~/app-files
    state: directory

- name: copy htaccess file to remote
  copy:
    src: htaccess
    dest: ~/app-files/htaccess

- name: copy htaccess into wordpress container
  shell: docker cp ~/app-files/htaccess {{ ascounseling.wp.container }}:/var/www/html/.htaccess

- name: set ownership of htaccess
  shell: docker exec {{ ascounseling.wp.container }} chown www-data:www-data /var/www/html/.htaccess

- name: restart wordpress
  shell: docker restart {{ ascounseling.wp.container }}
