---
- name: beton wordpress content container
  docker_container:
    image: wordpress:5.6
    name: beton-content
    state: stopped
    volumes:
      - /var/www/html

- name: beton db data container
  docker_container:
    image: mariadb:10.5
    name: beton-db-data
    state: stopped
    volumes:
      - /var/lib/mysql

- name: beton database
  docker_container:
    image: mariadb:10.5
    name: beton-db
    restart_policy: always
    env:
      MYSQL_DATABASE: "{{ beton.db.name }}"
      MYSQL_PASSWORD: "{{ beton.db.password }}"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: "{{ beton.db.user }}"
    volumes:
      - beton-db-data:/var/lib/mysql

- name: beton wordpress
  docker_container:
    image: wordpress:5.6
    name: beton-wp
    restart: yes
    restart_policy: always
    env:
      LETSENCRYPT_HOST: "{{ beton_hosts }}"
      VIRTUAL_HOST: "{{ beton_hosts }}"
      WORDPRESS_DB_NAME: "{{ beton.db.name }}"
      WORDPRESS_DB_PASSWORD: "{{ beton.db.password }}"
      WORDPRESS_DB_USER: "{{ beton.db.user }}"
    exposed_ports:
      - "80"
    links:
      - "beton-db:mysql"
    volumes:
      - beton-content:/var/www/html

- name: ensure app-files directory exists
  file:
    path: ~/app-files
    state: directory

- name: copy htaccess file to remote
  copy:
    src: htaccess
    dest: ~/app-files/htaccess

- name: copy htaccess into wordpress container
  shell: docker cp ~/app-files/htaccess {{ beton.wp.container }}:/var/www/html/.htaccess

- name: set ownership of htaccess
  shell: docker exec {{ beton.wp.container }} chown www-data:www-data /var/www/html/.htaccess

- name: restart wordpress
  shell: docker restart {{ beton.wp.container }}
