---
- name: biscuit-stage wordpress content container
  docker_container:
    image: wordpress:5.4.1
    name: biscuit-stage-content
    state: stopped
    volumes:
      - /var/www/html

- name: biscuit-stage db data container
  docker_container:
    image: mariadb:10.4
    name: biscuit-stage-db-data
    state: stopped
    volumes:
      - /var/lib/mysql

- name: biscuit-stage database
  docker_container:
    image: mariadb:10.4
    name: biscuit-stage-db
    restart_policy: always
    env:
      MYSQL_DATABASE: "{{ biscuit_stage.db.name }}"
      MYSQL_PASSWORD: "{{ biscuit_stage.db.password }}"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: "{{ biscuit_stage.db.user }}"
    volumes:
      - biscuit-stage-db-data:/var/lib/mysql

- name: biscuit-stage wordpress
  docker_container:
    image: wordpress:5.4.1
    name: biscuit-stage-wp
    restart: yes
    restart_policy: always
    env:
      HSTS: "off"
      # LETSENCRYPT_HOST: "{{ biscuit_stage_hosts }}"
      VIRTUAL_HOST: "{{ biscuit_stage_hosts }}"
      WORDPRESS_DB_NAME: "{{ biscuit_stage.db.name }}"
      WORDPRESS_DB_PASSWORD: "{{ biscuit_stage.db.password }}"
      WORDPRESS_DB_USER: "{{ biscuit_stage.db.user }}"
    exposed_ports:
      - "80"
    links:
      - "biscuit-stage-db:mysql"
    volumes:
      - biscuit-stage-content:/var/www/html

- name: biscuit-stage sftp
  docker_container:
    command: "{{ biscuit_stage.sftp.user }}:{{ biscuit_stage.sftp.password }}:1001"
    image: atmoz/sftp:latest
    name: biscuit-stage-ftp
    restart_policy: always
    ports:
      - "{{ biscuit_stage_sftp_port }}:22"
    volumes:
      - biscuit-stage-content:/home/biscuit/upload
