- name: biscuit-stage wordpress content container
  docker_container:
    image: wordpress:4.8-php7.1
    name: biscuit-stage-content
    state: present
    volumes:
      - /var/www/html

- name: biscuit-stage db data container
  docker_container:
    image: mariadb:10.2
    name: biscuit-stage-db-data
    state: present
    volumes:
      - /var/lib/mysql

- name: biscuit-stage database
  docker_container:
    image: mariadb:10.2
    name: biscuit-stage-db
    state: started
    env:
      MYSQL_DATABASE: "{{ biscuit_stage.db.name }}"
      MYSQL_PASSWORD: "{{ biscuit_stage.db.password }}"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: "{{ biscuit_stage.db.user }}"
    volumes:
      - biscuit-stage-db-data:/var/lib/mysql

- name: biscuit-stage wordpress
  docker_container:
    image: wordpress:4.8-php7.1
    name: biscuit-stage-wp
    restart: yes
    state: started
    env:
      HSTS: "off"
      LETSENCRYPT_HOST: "{{ biscuit_stage_hosts }}"
      VIRTUAL_HOST: "{{ biscuit_stage_hosts }}"
      WORDPRESS_DB_NAME: "{{ biscuit_stage.db.name }}"
      WORDPRESS_DB_PASSWORD: "{{ biscuit_stage.db.password }}"
      WORDPRESS_DB_USER: "{{ biscuit_stage.db.user }}"
    exposed_ports:
      - "80"
    links:
      - "biscuit-stage-db:mysql"
    volumes:
      - wp-demo-content:/var/www/html
