---
- name: bowen-work db backups container
  docker_container:
    image: mariadb:10
    name: bowen-work-db-backups
    state: present
    volumes:
      - /backups

- name: bowen-work wordpress content container
  docker_container:
    image: wordpress:5.3
    name: bowen-work-content
    state: present
    volumes:
      - /var/www/html

- name: bowen-work db data container
  docker_container:
    image: mariadb:10
    name: bowen-work-db-data
    state: present
    volumes:
      - /var/lib/mysql

- name: bowen-work database
  docker_container:
    image: mariadb:10
    name: bowen-work-db
    state: started
    env:
      MYSQL_DATABASE: "{{ bowen_work.db.name }}"
      MYSQL_PASSWORD: "{{ bowen_work.db.password }}"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: "{{ bowen_work.db.user }}"
    volumes:
      - bowen-work-db-backups:/backups
      - bowen-work-db-data:/var/lib/mysql

- name: bowen-work wordpress
  docker_container:
    image: wordpress:5.3
    name: bowen-work-web
    restart: yes
    state: started
    env:
      HSTS: "off"
      LETSENCRYPT_HOST: "{{ bowen_work_hosts }}"
      VIRTUAL_HOST: "{{ bowen_work_hosts }}"
      WORDPRESS_DB_NAME: "{{ bowen_work.db.name }}"
      WORDPRESS_DB_PASSWORD: "{{ bowen_work.db.password }}"
      WORDPRESS_DB_USER: "{{ bowen_work.db.user }}"
    exposed_ports:
      - "80"
    links:
      - "bowen-work-db:mysql"
    volumes:
      - bowen-work-content:/var/www/html

- name: bowen-work sftp
  docker_container:
    command: "{{ bowen_work.sftp.user }}:{{ bowen_work.sftp.password }}:1001"
    image: atmoz/sftp:latest
    name: bowen-work-ftp
    state: started
    ports:
      - "{{ bowen_work_sftp_port }}:22"
    volumes:
      - bowen-work-content:/home/alien/upload

