---
- name: commgap wordpress content container
  docker_container:
    image: wordpress:5.7
    name: commgap-content
    state: stopped
    volumes:
      - /var/www/html

- name: commgap db data container
  docker_container:
    image: mariadb:10.5
    name: commgap-db-data
    state: stopped
    volumes:
      - /var/lib/mysql

- name: commgap database
  docker_container:
    image: mariadb:10.5
    name: commgap-db
    restart_policy: always
    env:
      MYSQL_DATABASE: "{{ commgap.db.name }}"
      MYSQL_PASSWORD: "{{ commgap.db.password }}"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: "{{ commgap.db.user }}"
    volumes:
      - commgap-db-data:/var/lib/mysql

- name: commgap wordpress
  docker_container:
    image: wordpress:5.7
    name: commgap-wp
    restart: yes
    restart_policy: always
    env:
      LETSENCRYPT_HOST: "{{ commgap_hosts }}"
      VIRTUAL_HOST: "{{ commgap_hosts }}"
      WORDPRESS_DB_NAME: "{{ commgap.db.name }}"
      WORDPRESS_DB_PASSWORD: "{{ commgap.db.password }}"
      WORDPRESS_DB_USER: "{{ commgap.db.user }}"
    exposed_ports:
      - "80"
    links:
      - "commgap-db:mysql"
    volumes:
      - commgap-content:/var/www/html

- name: ensure app-files directory exists
  file:
    path: ~/app-files
    state: directory

- name: copy htaccess file to remote
  copy:
    src: htaccess
    dest: ~/app-files/htaccess

- name: copy htaccess into wordpress container
  shell: docker cp ~/app-files/htaccess {{ commgap.wp.container }}:/var/www/html/.htaccess

- name: set ownership of htaccess
  shell: docker exec {{ commgap.wp.container }} chown www-data:www-data /var/www/html/.htaccess

- name: restart wordpress
  shell: docker restart {{ commgap.wp.container }}
