---
- name: drupal-demo drupal content container
  docker_container:
    image: drupal:8
    name: drupal-demo-content
    state: stopped
    volumes:
      - /var/www/html

- name: drupal-demo db data container
  docker_container:
    image: mariadb:10
    name: drupal-demo-db-data
    state: stopped
    volumes:
      - /var/lib/mysql

- name: drupal-demo database
  docker_container:
    image: mariadb:10
    name: drupal-demo-db
    restart_policy: always
    env:
      MYSQL_DATABASE: "{{ drupal_demo.db.name }}"
      MYSQL_PASSWORD: "{{ drupal_demo.db.password }}"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: "{{ drupal_demo.db.user }}"
    volumes:
      - drupal-demo-db-data:/var/lib/mysql

- name: drupal-demo drupal
  docker_container:
    image: drupal:8
    name: drupal-demo-web
    restart: yes
    restart_policy: always
    env:
      HSTS: "off"
      LETSENCRYPT_HOST: "{{ drupal_demo_hosts }}"
      MYSQL_DATABASE: "{{ drupal_demo.db.name }}"
      MYSQL_PASSWORD: "{{ drupal_demo.db.password }}"
      MYSQL_USER: "{{ drupal_demo.db.user }}"
      VIRTUAL_HOST: "{{ drupal_demo_hosts }}"
    exposed_ports:
      - "80"
    links:
      - "drupal-demo-db:mysql"
    volumes:
      - drupal-demo-content:/var/www/html

- name: drupal-demo sftp
  docker_container:
    command: "{{ drupal_demo.sftp.user }}:{{ drupal_demo.sftp.password }}:1001"
    image: atmoz/sftp:latest
    name: drupal-demo-ftp
    restart_policy: always
    ports:
      - "{{ drupal_demo_sftp_port }}:22"
    volumes:
      - drupal-demo-content:/home/ddemo/upload
