---
- name: ensure aliencyborg directory is present
  file:
    path: "{{ hubdir }}/aliencyborg"
    state: directory

- name: clone or update dual-currency repository
  git:
    accept_hostkey: yes
    dest: "{{ hubdir }}/aliencyborg/dual-currency"
    key_file: "{{ homedir }}/.ssh/id_rsa"
    repo: "git@github.com:aliencyborg/dual-currency.git"
    update: yes
    version: master

- name: build docker image
  docker_image:
    force_source: yes
    name: dual-currency
    source: build
    tag: latest
    build:
      path: "{{ hubdir }}/aliencyborg/dual-currency"
      pull: no

- name: run docker container
  docker_container:
    expose: 80
    image: dual-currency:latest
    name: dual-currency
    env:
      HSTS: "off"
      LETSENCRYPT_HOST: "{{ dual_currency_hosts }}"
      PORT: "80"
      VIRTUAL_HOST: "{{ dual_currency_hosts }}"
