---
- name: ghost-demo db backups container
  docker_container:
    image: mariadb:10
    name: ghost-demo-db-backups
    state: stopped
    volumes:
      - /backups

- name: ghost-demo ghost content container
  docker_container:
    image: ghost:3
    name: ghost-demo-content
    state: stopped
    volumes:
      - /var/lib/ghost/content

- name: ghost-demo db data container
  docker_container:
    image: mariadb:10
    name: ghost-demo-db-data
    state: stopped
    volumes:
      - /var/lib/mysql

- name: ghost-demo database
  docker_container:
    image: mariadb:10
    name: ghost-demo-db
    restart: yes
    restart_policy: always
    env:
      MYSQL_DATABASE: "{{ ghost_demo.db.name }}"
      MYSQL_PASSWORD: "{{ ghost_demo.db.password }}"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: "{{ ghost_demo.db.user }}"
    volumes:
      - ghost-demo-db-backups:/backups
      - ghost-demo-db-data:/var/lib/mysql

- name: ghost-demo ghost
  docker_container:
    image: ghost:3
    name: ghost-demo
    restart: yes
    restart_policy: always
    env:
      HSTS: "off"
      LETSENCRYPT_HOST: "{{ ghost_demo_hosts }}"
      VIRTUAL_HOST: "{{ ghost_demo_hosts }}"
      database__client: mysql
      database__connection__database: "{{ ghost_demo.db.name }}"
      database__connection__host: mysql
      database__connection__password: "{{ ghost_demo.db.password }}"
      database__connection__user: "{{ ghost_demo.db.user }}"
      url: "{{ ghost_demo_url }}"
    links:
      - "ghost-demo-db:mysql"
    volumes:
      - ghost-demo-content:/var/www/html
