---
- name: mmm db backups container
  docker_container:
    image: mariadb:10
    name: mmm-db-backups
    state: stopped
    volumes:
      - /backups

- name: mmm wordpress content container
  docker_container:
    image: wordpress:5.3
    name: mmm-content
    state: stopped
    volumes:
      - /var/www/html

- name: mmm db data container
  docker_container:
    image: mariadb:10
    name: mmm-db-data
    state: stopped
    volumes:
      - /var/lib/mysql

- name: mmm database
  docker_container:
    image: mariadb:10
    name: mmm-db
    restart_policy: always
    state: started
    env:
      MYSQL_DATABASE: "{{ my_market_mentor.db.name }}"
      MYSQL_PASSWORD: "{{ my_market_mentor.db.password }}"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: "{{ my_market_mentor.db.user }}"
    volumes:
      - mmm-db-backups:/backups
      - mmm-db-data:/var/lib/mysql

- name: mmm wordpress
  docker_container:
    image: wordpress:5.3
    name: mmm-web
    restart: yes
    restart_policy: always
    state: started
    env:
      HSTS: "off"
      LETSENCRYPT_HOST: "{{ my_market_mentor_hosts }}"
      VIRTUAL_HOST: "{{ my_market_mentor_hosts }}"
      WORDPRESS_DB_NAME: "{{ my_market_mentor.db.name }}"
      WORDPRESS_DB_PASSWORD: "{{ my_market_mentor.db.password }}"
      WORDPRESS_DB_USER: "{{ my_market_mentor.db.user }}"
    exposed_ports:
      - "80"
    links:
      - "mmm-db:mysql"
    volumes:
      - mmm-content:/var/www/html

- name: mmm sftp
  docker_container:
    command: "{{ my_market_mentor.sftp.user }}:{{ my_market_mentor.sftp.password }}:1001"
    image: atmoz/sftp:latest
    name: mmm-ftp
    restart_policy: always
    state: started
    ports:
      - "{{ my_market_mentor_sftp_port }}:22"
    volumes:
      - mmm-content:/home/alien/upload

