---
- name: os-ticket db data container
  docker_container:
    image: mariadb:10
    name: os-ticket-db-data
    state: stopped
    volumes:
      - /var/lib/mysql

- name: os-ticket database
  docker_container:
    image: mariadb:10
    name: os-ticket-db
    restart_policy: always
    env:
      MYSQL_DATABASE: "{{ os_ticket.db.name }}"
      MYSQL_PASSWORD: "{{ os_ticket.db.password }}"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: "{{ os_ticket.db.user }}"
    volumes:
      - os-ticket-db-data:/var/lib/mysql

- name: os-ticket
  docker_container:
    image: osticket/osticket
    name: os-ticket
    restart: yes
    restart_policy: always
    env:
      LETSENCRYPT_HOST: "{{ os_ticket_hosts }}"
      VIRTUAL_HOST: "{{ os_ticket_hosts }}"
      MYSQL_PASSWORD: "{{ os_ticket.db.password }}"
      MYSQL_USER: "{{ os_ticket.db.user }}"
      MYSQL_DATABASE: "{{ os_ticket.db.name }}"
    exposed_ports:
      - "80"
    links:
      - "os-ticket-db:mysql"
