---
- name: ctp db backups container
  docker_container:
    image: mariadb:10.4
    name: ctp-wp-db-backups
    state: present
    volumes:
      - /backups

- name: ctp wordpress content container
  docker_container:
    image: wordpress:5.2
    name: ctp-wp-content
    state: present
    volumes:
      - /var/www/html

- name: ctp db data container
  docker_container:
    image: mariadb:10.4
    name: ctp-wp-db-data
    state: present
    volumes:
      - /var/lib/mysql

- name: ctp database
  docker_container:
    image: mariadb:10.4
    name: ctp-wp-db
    state: started
    env:
      MYSQL_PASSWORD: "{{ platypus.db.password }}"
      MYSQL_ROOT_PASSWORD: "{{ platypus.db.password }}"
    volumes:
      - ctp-wp-db-backups:/backups
      - ctp-wp-db-data:/var/lib/mysql

- name: ctp wordpress
  docker_container:
    image: wordpress:5.2
    name: ctp-wp-wp
    restart: yes
    state: started
    env:
      HSTS: "off"
      LETSENCRYPT_HOST: "{{ platypus_hosts }}"
      VIRTUAL_HOST: "{{ platypus_hosts }}"
      WORDPRESS_DB_PASSWORD: "{{ platypus.db.password }}"
    links:
      - "ctp-wp-db:mysql"
    volumes:
      - ctp-wp-content:/var/www/html

- name: ctp sftp
  docker_container:
    command: "{{ platypus.sftp.user }}:{{ platypus.sftp.password }}:1001"
    image: atmoz/sftp:latest
    name: ctp-wp-ftp
    state: started
    published_ports:
      - "{{ platypus_sftp_port }}:22"
    volumes:
      - ctp-wp-content:/home/alien/upload

