---
# become: yes
# become_user:

# vars:
#   backupdbcontainer
#   backupwpcontainer
#   dbcontainer:
#   dbname:
#   dbpassword:
#   dbuser:
#   wpcontainer:

- name: find and register the latest content backup
  shell: ls -At {{ wpbackupdir }} | grep {{ backupwpcontainer }} | head -n 1
  register: tarfile

- name: copy backup content tar into docker container
  shell: docker cp {{ wpbackupdir }}/{{ tarfile.stdout }} {{ wpcontainer }}:/var/www/html/

- name: unpack the content tarfile
  shell: docker exec {{ wpcontainer }} tar xfz {{ tarfile.stdout }}

- name: find and register the latest db backup
  shell: ls -At {{ dbbackupdir }} | grep {{ backupdbcontainer }} | head -n 1
  register: sqldump

- name: restore the sql backup to the database
  shell: cat {{ dbbackupdir }}/{{ sqldump.stdout }} | \
    docker exec -i {{ dbcontainer }} mysql -u{{ dbuser }} \
    -p{{ dbpassword }} {{ dbname }}
