---
- name: sabew wordpress content container
  docker_container:
    image: wordpress:5.5
    name: sabew-legacy-content
    state: stopped
    volumes:
      - /var/www/html

- name: sabew db data container
  docker_container:
    image: mariadb:10.5
    name: sabew-legacy-db-data
    state: stopped
    volumes:
      - /var/lib/mysql

- name: sabew database
  docker_container:
    image: mariadb:10.5
    name: sabew-legacy-db
    restart_policy: always
    env:
      MYSQL_DATABASE: "{{ sabew_legacy.db.name }}"
      MYSQL_PASSWORD: "{{ sabew_legacy.db.password }}"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: "{{ sabew_legacy.db.user }}"
    volumes:
      - sabew-legacy-db-data:/var/lib/mysql

- name: sabew wordpress
  docker_container:
    image: wordpress:5.5
    name: "{{ sabew_legacy.wp.container }}"
    restart: yes
    restart_policy: always
    env:
      HSTS: "off"
      LETSENCRYPT_HOST: "{{ sabew_legacy_hosts }}"
      VIRTUAL_HOST: "{{ sabew_legacy_hosts }}"
      WORDPRESS_DB_NAME: "{{ sabew_legacy.db.name }}"
      WORDPRESS_DB_PASSWORD: "{{ sabew_legacy.db.password }}"
      WORDPRESS_DB_USER: "{{ sabew_legacy.db.user }}"
    exposed_ports:
      - "80"
    links:
      - "sabew-legacy-db:mysql"
    volumes:
      - sabew-legacy-content:/var/www/html

- name: ensure app-files directory exists
  file:
    path: ~/app-files
    state: directory

- name: copy htaccess file to remote
  copy:
    src: htaccess
    dest: ~/app-files/htaccess

- name: copy htaccess into wordpress container
  shell: docker cp ~/app-files/htaccess {{ sabew_legacy.wp.container }}:/var/www/html/.htaccess

- name: set ownership of htaccess
  shell: docker exec {{ sabew_legacy.wp.container }} chown www-data:www-data /var/www/html/.htaccess

- name: restart wordpress
  shell: docker restart {{ sabew_legacy.wp.container }}

- name: sabew sftp
  docker_container:
    command: "{{ sabew_legacy.sftp.user }}:{{ sabew_legacy.sftp.password }}:1001"
    image: atmoz/sftp:latest
    name: sabew-legacy-ftp
    restart_policy: always
    ports:
      - "{{ sabew_legacy_sftp_port }}:22"
    volumes:
      - "sabew-legacy-content:/home/{{ sabew_legacy.sftp.user }}/upload"

- name: add group access permissions to ftp directory
  shell: docker exec sabew-legacy-ftp chmod -R g+w /home/{{ sabew_legacy.sftp.user }}
#- name: add ftp user to the www-data group
#shell: docker exec sabew-legacy-ftp usermod -g www-data {{ sabew_legacy.sftp.user }}
