---
- name: sabew wordpress content container (stage)
  docker_container:
    image: wordpress:5.7
    name: sabew-stage-content
    state: stopped
    volumes:
      - /var/www/html

- name: sabew db data container (stage)
  docker_container:
    image: mariadb:10.5
    name: sabew-stage-db-data
    state: stopped
    volumes:
      - /var/lib/mysql

- name: sabew database (stage)
  docker_container:
    image: mariadb:10.5
    name: sabew-stage-db
    restart_policy: always
    env:
      MYSQL_DATABASE: "{{ sabew_stage.db.name }}"
      MYSQL_PASSWORD: "{{ sabew_stage.db.password }}"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: "{{ sabew_stage.db.user }}"
    exposed_ports:
      - "3306"
    published_ports:
      - "0.0.0.0:{{ sabew_stage_db_port }}:3306/tcp"
    volumes:
      - sabew-stage-db-data:/var/lib/mysql

- name: sabew wordpress (stage)
  docker_container:
    image: wordpress:5.7
    name: sabew-stage-wp
    restart: yes
    restart_policy: always
    env:
      LETSENCRYPT_HOST: "{{ sabew_stage_hosts }}"
      VIRTUAL_HOST: "{{ sabew_stage_hosts }}"
      WORDPRESS_DB_NAME: "{{ sabew_stage.db.name }}"
      WORDPRESS_DB_PASSWORD: "{{ sabew_stage.db.password }}"
      WORDPRESS_DB_USER: "{{ sabew_stage.db.user }}"
    exposed_ports:
      - "80"
    links:
      - "sabew-stage-db:mysql"
    volumes:
      - sabew-stage-content:/var/www/html

- name: sabew sftp
  docker_container:
    command: "{{ sabew_stage.sftp.user }}:{{ sabew_stage.sftp.password }}:1001"
    image: atmoz/sftp:latest
    name: sabew-stage-ftp
    restart_policy: always
    ports:
      - "{{ sabew_stage_sftp_port }}:22"
    volumes:
      - "sabew-stage-content:/home/{{ sabew_stage.sftp.user }}/upload"

- name: ensure app-files directory exists
  file:
    path: ~/app-files
    state: directory

- name: copy htaccess file to remote
  copy:
    src: htaccess
    dest: ~/app-files/htaccess

- name: copy htaccess into wordpress container
  shell: docker cp ~/app-files/htaccess {{ sabew_stage.wp.container }}:/var/www/html/.htaccess

- name: set ownership of htaccess
  shell: docker exec {{ sabew_stage.wp.container }} chown www-data:www-data /var/www/html/.htaccess

- name: restart wordpress
  shell: docker restart {{ sabew_stage.wp.container }}
