---
- name: ensure app-files directory exists
  file:
    path: ~/app-files
    state: directory

- name: copy init-db script to remote
  copy:
    src: init-sabew-db.sh
    dest: ~/app-files/init-sabew-db.sh

- name: copy sql file to remote
  copy:
    src: membership_sabew.sql
    dest: ~/app-files/membership_sabew.sql

- name: sabew pg data container
  docker_container:
    image: postgres:13
    name: sabew-pg-data
    state: stopped
    volumes:
      - /var/lib/postgresql/data

- name: sabew pg database
  docker_container:
    image: postgres:13
    name: sabew-pg-db
    restart_policy: always
    env:
      POSTGRES_DB: "{{ sabew_pg.db.name }}"
      POSTGRES_USER: "{{ sabew_pg.db.user }}"
      POSTGRES_PASSWORD: "{{ sabew_pg.db.password }}"
    exposed_ports:
      - "5432"
    published_ports:
      - "0.0.0.0:{{ sabew_pg_db_port }}:5432/tcp"
    volumes:
      - sabew-pg-data:/var/lib/postgresql/data
      - ./app-files/init-sabew-db.sh:/docker-entrypoint-initdb.d/01-init-db.sh
      - ./app-files/membership_sabew.sql:/docker-entrypoint-initdb.d/02-create_tables.sql

- name: adminer
  docker_container:
    image: adminer
    exposed_ports:
      - "8080"
    published_ports:
      - "0.0.0.0:{{ sabew_pg_adminer_port }}:8080/tcp"
