---
- name: shahbaz wordpress content container
  docker_container:
    image: wordpress:5.5
    name: shahbaz-content
    state: stopped
    volumes:
      - /var/www/html

- name: shahbaz db data container
  docker_container:
    image: mariadb:10.4
    name: shahbaz-db-data
    state: stopped
    volumes:
      - /var/lib/mysql

- name: shahbaz database
  docker_container:
    image: mariadb:10.4
    name: shahbaz-db
    restart_policy: always
    env:
      MYSQL_DATABASE: "{{ shahbaz.db.name }}"
      MYSQL_PASSWORD: "{{ shahbaz.db.password }}"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: "{{ shahbaz.db.user }}"
    volumes:
      - shahbaz-db-data:/var/lib/mysql

- name: shahbaz wordpress
  docker_container:
    image: wordpress:5.5
    name: shahbaz-wp
    restart: yes
    restart_policy: always
    env:
      HSTS: "off"
      LETSENCRYPT_HOST: "{{ shahbaz_hosts }}"
      VIRTUAL_HOST: "{{ shahbaz_hosts }}"
      WORDPRESS_DB_NAME: "{{ shahbaz.db.name }}"
      WORDPRESS_DB_PASSWORD: "{{ shahbaz.db.password }}"
      WORDPRESS_DB_USER: "{{ shahbaz.db.user }}"
    exposed_ports:
      - "80"
    links:
      - "shahbaz-db:mysql"
    volumes:
      - shahbaz-content:/var/www/html

- name: shahbaz sftp
  docker_container:
    command: "{{ shahbaz.sftp.user }}:{{ shahbaz.sftp.password }}:1001"
    image: atmoz/sftp:latest
    name: shahbaz-ftp
    restart_policy: always
    ports:
      - "{{ shahbaz_sftp_port }}:22"
    volumes:
      - shahbaz-content:/home/shahbaz/upload
