---
- name: sudo livebook content container
  docker_container:
    image: livebook/livebook:edge
    name: sudo-livebook-content
    state: stopped
    volumes:
      - /data

- name: sudo livebook
  docker_container:
    image: livebook/livebook:edge
    name: sudo-livebook
    recreate: yes
    restart: yes
    restart_policy: always
    env:
      LETSENCRYPT_HOST: "{{ sudo_livebook_hosts }}"
      LIVEBOOK_PASSWORD: "{{ sudo_livebook.password }}"
      VIRTUAL_HOST: "{{ sudo_livebook_hosts }}"
      VIRTUAL_PORT: "8080"
    exposed_ports:
      - "8080"
    volumes:
      sudo-livebook-content:/data
