---
- name: sudo-science db backups container
  docker_container:
    image: mariadb:10
    name: sudo-science-db-backups
    state: stopped
    volumes:
      - /backups

- name: sudo-science ghost content container
  docker_container:
    image: ghost:3
    name: sudo-science-content
    state: stopped
    volumes:
      - /var/lib/ghost/content

- name: sudo-science db data container
  docker_container:
    image: mariadb:10
    name: sudo-science-db-data
    state: stopped
    volumes:
      - /var/lib/mysql

- name: sudo-science database
  docker_container:
    image: mariadb:10
    name: sudo-science-db
    restart: yes
    restart_policy: always
    env:
      MYSQL_DATABASE: "{{ sudo_science.db.name }}"
      MYSQL_PASSWORD: "{{ sudo_science.db.password }}"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: "{{ sudo_science.db.user }}"
    volumes:
      - sudo-science-db-backups:/backups
      - sudo-science-db-data:/var/lib/mysql

- name: sudo-science ghost
  docker_container:
    image: ghost:3
    name: sudo-science-ghost
    restart: yes
    restart_policy: always
    env:
      HSTS: "off"
      LETSENCRYPT_HOST: "{{ sudo_science_ghost_hosts }}"
      VIRTUAL_HOST: "{{ sudo_science_ghost_hosts }}"
      VIRTUAL_PORT: "2368"
      database__client: mysql
      database__connection__database: "{{ sudo_science.db.name }}"
      database__connection__host: mysql
      database__connection__password: "{{ sudo_science.db.password }}"
      database__connection__user: "{{ sudo_science.db.user }}"
      url: "{{ sudo_science_ghost_url }}"
    exposed_ports:
      - "2368"
    links:
      - "sudo-science-db:mysql"
    volumes:
      - sudo-science-content:/var/www/html
