---
- name: tw-donnie wordpress content container
  docker_container:
    image: wordpress:5.6
    name: "{{ tw_donnie.wp.content }}"
    state: stopped
    volumes:
      - /var/www/html

- name: tw-donnie db data container
  docker_container:
    image: mariadb:10
    name: tw-donnie-db-data-2
    state: stopped
    volumes:
      - /var/lib/mysql

- name: tw-donnie database
  docker_container:
    image: mariadb:10
    name: tw-donnie-db
    recreate: yes
    restart_policy: always
    env:
      MYSQL_DATABASE: "{{ tw_donnie.db.name }}"
      MYSQL_PASSWORD: "{{ tw_donnie.db.password }}"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: "{{ tw_donnie.db.user }}"
    volumes:
      - tw-donnie-db-data-2:/var/lib/mysql

- name: tw-donnie wordpress
  docker_container:
    image: wordpress:5.6
    name: "{{ tw_donnie.wp.container }}"
    recreate: yes
    restart: yes
    restart_policy: always
    env:
      LETSENCRYPT_HOST: "{{ tw_donnie_hosts }}"
      VIRTUAL_HOST: "{{ tw_donnie_hosts }}"
      WORDPRESS_DB_NAME: "{{ tw_donnie.db.name }}"
      WORDPRESS_DB_PASSWORD: "{{ tw_donnie.db.password }}"
      WORDPRESS_DB_USER: "{{ tw_donnie.db.user }}"
    exposed_ports:
      - "80"
    links:
      - "tw-donnie-db:mysql"
    volumes:
      - "{{ tw_donnie.wp.content }}:/var/www/html"

- name: tw-donnie sftp
  docker_container:
    command: "{{ tw_donnie.sftp.user }}:{{ tw_donnie.sftp.password }}:1001"
    image: atmoz/sftp:latest
    name: tw-donnie-ftp
    restart_policy: always
    ports:
      - "{{ tw_donnie_sftp_port }}:22"
    volumes:
      - "{{ tw_donnie.wp.content }}:/home/{{ tw_donnie.sftp.user }}/upload"

- name: ensure app-files directory exists
  file:
    path: ~/app-files
    state: directory

- name: copy htaccess file to remote
  copy:
    src: ../files/htaccess
    dest: ~/app-files/htaccess

- name: copy htaccess into wordpress container
  shell: docker cp ~/app-files/htaccess {{ tw_donnie.wp.container }}:/var/www/html/.htaccess

- name: set ownership of htaccess
  shell: docker exec {{ tw_donnie.wp.container }} chown www-data:www-data /var/www/html/.htaccess

- name: restart wordpress
  shell: docker restart {{ tw_donnie.wp.container }}
