---
- name: tw-sammy wordpress content container
  docker_container:
    image: wordpress:5.6
    name: tw-sammy-content
    state: stopped
    volumes:
      - /var/www/html

- name: tw-sammy db data container
  docker_container:
    image: mariadb:10
    name: tw-sammy-db-data
    state: stopped
    volumes:
      - /var/lib/mysql

- name: tw-sammy database
  docker_container:
    image: mariadb:10
    name: tw-sammy-db
    restart_policy: always
    env:
      MYSQL_DATABASE: "{{ tw_sammy.db.name }}"
      MYSQL_PASSWORD: "{{ tw_sammy.db.password }}"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: "{{ tw_sammy.db.user }}"
    volumes:
      - tw-sammy-db-data:/var/lib/mysql

- name: tw-sammy wordpress
  docker_container:
    image: wordpress:5.6
    name: tw-sammy-wp
    restart: yes
    restart_policy: always
    env:
      LETSENCRYPT_HOST: "{{ tw_sammy_hosts }}"
      VIRTUAL_HOST: "{{ tw_sammy_hosts }}"
      WORDPRESS_DB_NAME: "{{ tw_sammy.db.name }}"
      WORDPRESS_DB_PASSWORD: "{{ tw_sammy.db.password }}"
      WORDPRESS_DB_USER: "{{ tw_sammy.db.user }}"
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME', 'https://www.samanthajlive.com');
        define('WP_SITEURL', 'https://www.samanthajlive.com');
    exposed_ports:
      - "80"
    links:
      - "tw-sammy-db:mysql"
    volumes:
      - tw-sammy-content:/var/www/html

- name: ensure app-files directory exists
  file:
    path: ~/app-files
    state: directory

- name: copy uploads.ini file to remote
  copy:
    src: ../files/uploads.ini
    dest: ~/app-files/uploads.ini

- name: copy uploads.ini into wordpress container
  shell: docker cp ~/app-files/uploads.ini {{ tw_sammy.wp.container }}:/usr/local/etc/php/conf.d/uploads.ini

- name: set ownership of uploads.ini
  shell: docker exec {{ tw_sammy.wp.container }} chown www-data:www-data /usr/local/etc/php/conf.d/uploads.ini

- name: restart wordpress
  shell: docker restart {{ tw_sammy.wp.container }}

# - name: enable apache mod_rewrite
#   shell: docker exec {{ tw_sammy.wp.container }} a2enmod rewrite

# - name: restart apache in container
#   shell: docker exec {{ tw_sammy.wp.container }} service apache2 restart
