---
- name: veta-wp wordpress content container
  docker_container:
    image: wordpress:5.5
    name: veta-wp-content
    state: stopped
    volumes:
      - /var/www/html

- name: veta-wp db data container
  docker_container:
    image: mariadb:10
    name: veta-wp-db-data
    state: stopped
    volumes:
      - /var/lib/mysql

- name: veta-wp database
  docker_container:
    image: mariadb:10
    name: veta-wp-db
    restart_policy: always
    env:
      MYSQL_DATABASE: "{{ veta.db.name }}"
      MYSQL_PASSWORD: "{{ veta.db.password }}"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: "{{ veta.db.user }}"
    volumes:
      - veta-wp-db-data:/var/lib/mysql

- name: veta-wp wordpress
  docker_container:
    image: wordpress:5.5
    name: veta-wp-web
    restart: yes
    restart_policy: always
    env:
      HSTS: "off"
      LETSENCRYPT_HOST: "{{ veta_hosts }}"
      VIRTUAL_HOST: "{{ veta_hosts }}"
      WORDPRESS_DB_NAME: "{{ veta.db.name }}"
      WORDPRESS_DB_PASSWORD: "{{ veta.db.password }}"
      WORDPRESS_DB_USER: "{{ veta.db.user }}"
    exposed_ports:
      - "80"
      - "443"
    links:
      - "veta-wp-db:mysql"
    volumes:
      - veta-wp-content:/var/www/html

- name: veta-wp sftp
  docker_container:
    command: "{{ veta.sftp.user }}:{{ veta.sftp.password }}:1001"
    image: atmoz/sftp:latest
    name: veta-wp-ftp
    restart_policy: always
    ports:
      - "{{ veta_sftp_port }}:22"
    volumes:
      - veta-wp-content:/home/alien/upload
