---
hostname: machine
username: human
userpassword: "secret$$$hash$$$"
workdir: "/home/human/webapps"
# see docs.ansible.com/ansible/latest/reference_appendices/faq.html#how-do-i-generate-crypted-passwords-for-the-user-module

drupal_demo_domain: drupal-demo.example.org
drupal_demo_username: demo
drupal_demo_password: demo1234
drupal_demo_sftp_port: 49152

mmm_domain: another-wordpress.example.com
mmm_sftp_username: sftpusername
mmm_sftp_password: sftppassword
mmm_sftp_port: 49153