---
- hosts: webservers
  tasks:
    - name: register timestamp
      tags: [time]
      set_fact:
        timestamp: '{{ ansible_date_time.iso8601_basic_short }}'

    - name: debug timestamp
      tags: [time]
      debug:
        msg: 'timestamp: {{ timestamp }}'

    # - ansible.builtin.include_tasks: ../tasks/backup-wordpress.yml
    #   tags: [tw, donnie, backup]
    #   vars:
    #     dbcontainer: '{{ tw_donnie.db.container }}'
    #     dbname: '{{ tw_donnie.db.name }}'
    #     dbpassword: '{{ tw_donnie.db.password }}'
    #     dbuser: '{{ tw_donnie.db.user }}'
    #     wpcontainer: '{{ tw_donnie.wp.container }}'

    - ansible.builtin.include_tasks: ../tasks/backup-wordpress.yml
      tags: [tw, oceanic, backup]
      vars:
        dbcontainer: '{{ tw_oceanic.db.container }}'
        dbname: '{{ tw_oceanic.db.name }}'
        dbpassword: '{{ tw_oceanic.db.password }}'
        dbuser: '{{ tw_oceanic.db.user }}'
        wpcontainer: '{{ tw_oceanic.wp.container }}'

    - ansible.builtin.include_tasks: ../tasks/backup-wordpress.yml
      tags: [tw, sammy, backup]
      vars:
        dbcontainer: '{{ tw_sammy.db.container }}'
        dbname: '{{ tw_sammy.db.name }}'
        dbpassword: '{{ tw_sammy.db.password }}'
        dbuser: '{{ tw_sammy.db.user }}'
        wpcontainer: '{{ tw_sammy.wp.container }}'

    - ansible.builtin.include_tasks: ../tasks/archive-backups.yml
      tags: archive

    - ansible.builtin.include_tasks: ../tasks/fetch-archives.yml
      tags: archive

  vars_files:
    # - ../play_vars/tw-donnie.yml
    - ../play_vars/tw-oceanic.yml
    - ../play_vars/tw-sammy.yml
