---
- hosts: webservers
  tasks:
    # - ansible.builtin.include_tasks: ../tasks/tw-donnie.yml
    #   tags: [tw, donnie]
    - ansible.builtin.include_tasks: ../tasks/tw-oceanic.yml
      tags: [tw, oceanic]
    - ansible.builtin.include_tasks: ../tasks/tw-sammy.yml
      tags: [tw, sammy]
    - ansible.builtin.include_tasks: ../tasks/ovc-wp.yml
      tags: [ovc, wp]
  vars_files:
    # - ../play_vars/tw-donnie.yml
    - ../play_vars/tw-oceanic.yml
    - ../play_vars/tw-sammy.yml
    - ../play_vars/ovc_wp.yml
